title: Bitcoin Plebs
description: A zero-to-hero bitcoin pleb training program on bitcoin testnet
theme: just-the-docs

color_scheme: bitcoin_plebs_dark.scss

url: bitcoinplebs.org

# Multilanguage support
languages: ["en", "hu"]
default_language: "en"
exclude_from_localization: ["javascript", "images", "css", "assets", "README.md"]
parallel_localization: true

plugins:
  - jekyll-default-layout
  - jekyll-target-blank
  - jekyll-redirect-from

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Aux links for the upper right navigation
aux_links:
  "Bitcoin Plebs on GitHub":
    - "https://github.com/Pleb5/Pleb5.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


# External navigation links
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs
#    hide_icon: false # set to true to hide the external link icon - defaults to false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/img/favicon.png"

# Footer configuration - use custom footer content
footer_content: '<a href="https://github.com/Pleb5/Pleb5.github.io" target="_blank" rel="noopener noreferrer">Bitcoin Plebs on GitHub</a>'

# Additional custom footer can be added via this file
footer: "footer_custom.html"


